# Generated by Django 4.2.13 on 2024-07-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_name', models.CharField(max_length=50)),
                ('audio_file', models.FileField(upload_to='audio_files/')),
            ],
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
